definitions:
  schema.OpeningResponse:
    properties:
      company:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: integer
      link:
        type: string
      location:
        type: string
      remote:
        type: boolean
      role:
        type: string
      salary:
        type: integer
      updatedAt:
        type: string
    type: object
  service.ErrorOutput:
    properties:
      message:
        type: string
      statusCode:
        type: string
    type: object
  service.OpeningCreateInput:
    properties:
      company:
        type: string
      link:
        type: string
      location:
        type: string
      remote:
        type: boolean
      role:
        type: string
      salary:
        type: integer
    type: object
  service.OpeningCreateOutput:
    properties:
      data:
        $ref: '#/definitions/schema.OpeningResponse'
      message:
        type: string
    type: object
  service.OpeningDeleteOutput:
    properties:
      data:
        $ref: '#/definitions/schema.OpeningResponse'
      message:
        type: string
    type: object
  service.OpeningFindOutput:
    properties:
      data:
        $ref: '#/definitions/schema.OpeningResponse'
      message:
        type: string
    type: object
  service.OpeningListOutput:
    properties:
      data:
        items:
          $ref: '#/definitions/schema.OpeningResponse'
        type: array
      message:
        type: string
    type: object
  service.OpeningUpdateInput:
    properties:
      company:
        type: string
      link:
        type: string
      location:
        type: string
      remote:
        type: boolean
      role:
        type: string
      salary:
        type: integer
    type: object
  service.OpeningUpdateOutput:
    properties:
      data:
        $ref: '#/definitions/schema.OpeningResponse'
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /opening:
    delete:
      consumes:
      - application/json
      description: Delete job opening
      parameters:
      - description: Opening id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.OpeningDeleteOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/service.ErrorOutput'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/service.ErrorOutput'
      summary: Delete opening
      tags:
      - Openings
    get:
      consumes:
      - application/json
      description: Find List Openings
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.OpeningListOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/service.ErrorOutput'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/service.ErrorOutput'
      summary: List Openings
      tags:
      - Openings
    post:
      consumes:
      - application/json
      description: Create a new job opening
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/service.OpeningCreateInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.OpeningCreateOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/service.ErrorOutput'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/service.ErrorOutput'
      summary: Create opening
      tags:
      - Openings
    put:
      consumes:
      - application/json
      description: Update job opening
      parameters:
      - description: Opening id
        in: path
        name: id
        required: true
        type: integer
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/service.OpeningUpdateInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.OpeningUpdateOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/service.ErrorOutput'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/service.ErrorOutput'
      summary: Update opening
      tags:
      - Openings
swagger: "2.0"
